const todosDetalhes = [
  {
    cod: "262490",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },

  {
    cod: "264750",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },

  {
    cod: "297330",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },

  {
    cod: "269210",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },

  {
    cod: "270790",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },

  {
    cod: "271150",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },

  {
    cod: "271510",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },

  {
    cod: "263610",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },

  {
    cod: "229650",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "",
    boletoMiner: "",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },

  {
    cod: "263710",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "264150",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "271830",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "X",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "266710",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "270970",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "271350",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "261430",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "263450",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "264250",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "264290",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "264670",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "264710",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "264730",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "264950",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "265490",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "265510",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "267130",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "267890",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "271210",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "272330",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "264950",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "RENAVAM",
  },
  {
    cod: "",
    fotoOrgao: "X",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "",
    originaria: "",
    parametros: "",
  },
  {
    cod: "113200",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "",
    boletoMiner: "",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "126200",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "",
    boletoMiner: "",
    originaria: "X",
    parametros: "RENAVAM",
  },
  {
    cod: "102100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "106100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "107100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "108100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "109100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "110100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "x",
    originaria: "",
    parametros: "PLACA E RENAVAM/CHASSI",
  },
  {
    cod: "113100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E CHASSI",
  },
  {
    cod: "112100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "114100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "117100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA",
  },
  {
    cod: "118100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "116100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "RENAVAM",
  },
  {
    cod: "116100",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E AUTO E CNPJ E COD ORGAO",
  },
  {
    cod: "119100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "RENAVAM",
  },
  {
    cod: "120100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "123100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "121100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "125100",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "300",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "116100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "X",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "268750",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "",
    boletoMiner: "",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "266190",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "RENAVAM",
  },
  {
    cod: "115100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "262190",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "",
    boletoMiner: "",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "262910",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "X",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "263770",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA, RENAVAM E CPF/CNPJ",
  },
  {
    cod: "213890",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "264770",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "202550",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "RENAVAN OU CHASSI OU AUTO",
  },
  {
    cod: "270710",
    fotoOrgao: "X",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "270750",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "270990",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "271450",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "260010",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "",
    boletoMiner: "",
    originaria: "",
    parametros: "PLACA",
  },
  {
    cod: "271070",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "238490",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "RENAVAM",
  },
  {
    cod: "",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "121100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "103100",
    fotoOrgao: "",
    fotoMiner: "",
    espelhoNoticOrgao: "",
    espelhoNoticMiner: "",
    extratoOrgao: "X",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "",
    originaria: "",
    parametros: "CHASSI OU RENAVAM",
  },
  {
    cod: "263130",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "271570",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "PLACA E RENAVAM",
  },
  {
    cod: "262130",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "RENAVAM",
  },
  {
    cod: "262850",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "RENAVAM",
  },
  {
    cod: "265450",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "RENAVAM",
  },
  {
    cod: "265890",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "RENAVAM",
  },
  {
    cod: "272370",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "RENAVAM",
  },
  {
    cod: "107200",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "270990",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "270770",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "X",
    parametros: "PLACA E RENAVAM (cpf 00000000000)",
  },
  {
    cod: "281790",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "213890",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "203010",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "225210",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "290670",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "207270",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "206050",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "217590",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "208030",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "290670",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "234490",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "265650",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "261370",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "289850",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "221390",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "268410",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "292270",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "201390",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "244450",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "298410",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "209630",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "203010",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "209210",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "237810",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "212190",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "224270",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "298350",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "204430",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "117200",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "X",
    extratoMiner: "X",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
  {
    cod: "105200",
    fotoOrgao: "X",
    fotoMiner: "X",
    espelhoNoticOrgao: "X",
    espelhoNoticMiner: "X",
    extratoOrgao: "",
    extratoMiner: "",
    boletoOrgao: "X",
    boletoMiner: "X",
    originaria: "",
    parametros: "",
  },
];
export { todosDetalhes };
